backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: 'public/images' # Media files will be stored in the repo under...
public_folder: '/images' # The src attribute for uploaded media will begin...
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/pages/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template
    filter:
      field: draft
      value: false
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../../components/layouts/post.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          time_format: 'false',
          format: 'MM-DD-YYYY',
          picker_utc: true,
        }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Description', name: 'desc', widget: 'text' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: true,
          options:
            [
              { label: 'General Piracy', value: 'general-piracy' },
              { label: 'Licit Guides', value: 'licit-guides' },
              { label: 'Servarr', value: 'servarr' },
              { label: 'Music Piracy', value: 'music-piracy' },
            ],
        }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
# slug: activate-windows-free
# author: 'Cain'
